### ISSUE TITLE
get_receivers

### ISSUE THREAD

**Issue by jreubens** [inbo/etn#41] opened 2018-05-07 11:31 UTC
currently the get_receivers function links receivers to a network.
Some remarks on this:
- output gives an overview of all deployment that occur/have occurred. Thus receivers can be present multiple times. I don't think this is a wanted output. Should be unique receives to my opinion
- currently you can only link to the network_project. should be extended to animal_project as well
- next to projects you should also be able to view and filter on owner_organisation. The output gives a number. should be a name.... TO be able to filter on it using 'get_receivers(my_con, network_project = "INBO")' I guess this info needs to be added to 'my_projects' output first...

**Comment by stijnvanhoey** [comment] 2018-05-28 19:04
@jreubens are these nice to have features are rather required package functionalities to tackle for the first release?

**Comment by jreubens** [comment] 2018-05-29 08:10
The ones in this issue are more than 'nice to have' thus should be part of the first release to my opinion

**Comment by damianooldoni** [comment] 2018-05-29 18:12
@stijnvanhoey , @jreubens : nice. I will find the needed time to implement this features and update documentation and tests before the start of my 10 days holidays on Wed 6th of June. :+1:

**Comment by stijnvanhoey** [comment] 2018-05-29 18:13
I agree on point 

1. receivers should not provide information on all deployments

3. as the `owner_group_fk` can [now](https://github.com/inbo/etn/issues/42#issuecomment-392708047) be linked to the `etn_group`, we can add this to the table

I do not agree on point

2. animal_projects are linked to animals; in order to be able to filter network projects as well, the issue is similar to #43, but now the other way around. For all detections, which receivers got signal from which tags, tags linked to tag_releas, to animal to animal_project... That's a long road to just add this filter... 

It depends on the necessity, but I see the discussion of point 2 similar to #43, so let's discuss this kind of filter there. This issus focuses on the solving of point 1 and 3, a todo for me and damiano.

**Comment by peterdesmet** [comment] 2020-03-20 10:21
Trying to close this issue.

> 1. Should be unique receives to my opinion

Agree, this is now the case. `network_project_code` is no longer a parameter

> 2. ... currently you can only link to the network_project. should be extended to animal_project as well

As mentioned by @stijnvanhoey, let's not do this: it's a complicated way to get there and doesn't really make sense in the model.

> 3. ...next to projects you should also be able to view and filter on owner_organisation

As mentioned by @stijnvanhoey in https://github.com/inbo/etn/pull/54#issue-191450536, you can do this with `get_receivers(con) %>% filter(owner_organization == "INBO")` @jreubens @IPauwels @PieterjanVerhelst please create a new issue if you think `owner_organization` should be a parameter in `get_receivers()` (and then also `get_tags(()`)

**Closed by peterdesmet** 2020-03-20 10:21 UTC
Labels: enhancement
