### ISSUE TITLE
owner_organization in get_receivers() and get_tags()

### ISSUE THREAD

**Issue by IPauwels** [inbo/etn#112] opened 2020-03-20 16:25 UTC
I would think it is useful to be able to filter on owner_organization for getting receivers and tags, so to add owner_organisation as a parameter to get_receivers() and get_tags().

@jreubens @PieterjanVerhelst, what is your opinion?

**Comment by PieterjanVerhelst** [comment] 2020-03-20 16:29
Is this necessary at 'R-level' or does this practicality at the ETN database suffice?

**Comment by IPauwels** [comment] 2020-03-20 16:41
Actually only at ETN database indeed.. I would think..

**Comment by jreubens** [comment] 2020-03-20 19:53
In most cases webapp will be sufficient, but I'm in favour as well to have this at R-level.
If you want to do meta-analyses on e.g. 'brand use' in Europe over different users, this kind of info becomes interesting.

**Comment by peterdesmet** [comment] 2020-03-21 15:02
@IPauwels I guess you opened this issue in response to https://github.com/inbo/etn/issues/41#issuecomment-601626126, see also issue #110 where the consistency of this type of information is discussed. There are a couple of questions there

@jreubens so you _are_ in favour of adding this as a parameter, but I wonder if it's typical enough as a use case to add it. I'm in favour of keeping it in the results you get back, but I wonder if it needs to be a parameter. Note that you can always do `get_receivers() %>% filter(owner_organization == "INBO")`. Also, you mention *brand use*, but that seems to be more related to the field `manufacturer`, no?

**Comment by jreubens** [comment] 2020-03-27 06:55
@peterdesmet I agree with your comments.. thus we can leave as is

**Comment by peterdesmet** [comment] 2020-03-27 08:48
With so many issues about `owner_organization`, I failed to see this is a duplicate of #117. I'll close this one here and discuss over there.

**Closed by peterdesmet** 2020-03-27 08:48 UTC
